/*
-- Query: SELECT * FROM portfolio.stars
LIMIT 0, 1000

-- Date: 2019-07-15 09:46
*/
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (1,'Big Bob-omb on the Summit',1);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (2,'Footrace with Koopa the Quick',1);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (3,'Shoot to the Island in the Sky',1);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (4,'Find the 8 Red Coins',1);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (5,'Mario Wings to the Sky',1);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (6,'Behind Chain Chomp\'s Gate',1);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (7,'BoB 100',1);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (8,'Chip off Whomp\'s Block',2);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (9,'To the Top of the Fortress',2);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (10,'Shoot into the Wild Blue',2);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (11,'Red Coins on the Floating Isle',2);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (12,'Fall onto the Caged Island',2);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (13,'Blast Away the Wall',2);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (14,'WF 100',2);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (15,'Plunder in the Sunken Ship',3);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (16,'Can the Eel Come out and Play?',3);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (17,'Treasure of the Ocean Cave',3);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (18,'Red Coins on the Ship Afloat',3);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (19,'Blast to the Stone Pillar',3);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (20,'Through the Jet Stream',3);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (21,'JRB 100',3);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (22,'Slip Slidin\' Away',4);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (23,'Li\'l Penguin Lost',4);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (24,'Big Penguin Race',4);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (25,'Frosty Slide for 8 Red Coins',4);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (26,'Snowman\'s Lost his Head',4);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (27,'Wall Kicks will Work',4);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (28,'CCM 100',4);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (29,'Go on a Ghost Hunt',5);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (30,'Ride Big Boo\'s Merry-Go-Round',5);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (31,'Secret of the Haunted Books',5);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (32,'Seek the 8 Red Coins',5);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (33,'Big Boo\'s Balcony',5);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (34,'Eye to Eye in the Secret Room',5);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (35,'BBH 100',5);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (36,'Swimming Beast in the Cavern',6);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (37,'Elevate for 8 Red Coins',6);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (38,'Metal-Head Mario Can Move!',6);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (39,'Navigating the Toxic Maze',6);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (40,'A-Maze-ing Emergency Exit',6);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (41,'Watch for the Rolling Rocks',6);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (42,'HMC 100',6);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (43,'Boil the Big Bully',7);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (44,'Bully the Bullies',7);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (45,'8-Coin Puzzle with 15 Pieces',7);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (46,'Red-Hot Log Rolling',7);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (47,'Hot-Foot-It into the Volcano',7);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (48,'Elevator Tour in the Volcano',7);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (49,'LLL 100',7);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (50,'In the Talons of the Big Bird',8);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (51,'Shining Atop the Pyramid',8);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (52,'Inside the Ancient Pyramid',8);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (53,'Stand Tall on the Four Pillars',8);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (54,'Free Flying for 8 Red Coins',8);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (55,'Pyramid Puzzle',8);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (56,'SSL 100',8);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (57,'Board Bowser\'s Sub',9);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (58,'Chests in the Current',9);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (59,'Pole-Jumping for Red Coins',9);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (60,'Through the Jet Stream',9);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (61,'The Manta Ray\'s Reward',9);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (62,'Collect the Caps',9);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (63,'DDD 100',9);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (64,'Snowman\'s Big Head',10);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (65,'Chill with the Bully',10);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (66,'In the Deep Freeze',10);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (67,'Whirl from the Freezing Pond',10);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (68,'Shell Shreddin\' for 8 Red Coins',10);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (69,'Into the Igloo',10);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (70,'SL 100',10);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (71,'Shocking Arrow Lifts!',11);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (72,'Top O\' The Town',11);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (73,'Secrets in the Shallows & Sky',11);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (74,'Express Elevators--Hurry Up!',11);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (75,'Go to Town for Red Coins',11);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (76,'Quick Race through Downtown',11);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (77,'WDW 100',11);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (78,'Scale the Mountain',12);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (79,'Mystery of the Monkey Cage',12);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (80,'Scary \'Shrooms, Red Coins',12);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (81,'Mysterious Mountainside',12);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (82,'Breathtaking View from Bridge',12);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (83,'Blast to the Lonely Mushroom',12);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (84,'TTM 100',12);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (85,'Pluck the Piranha Flower',13);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (86,'The Tip Top of the Huge Island',13);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (87,'Rematch with Koopa the Quick',13);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (88,'Five Itty Bitty Secrets',13);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (89,'Wiggler\'s Red Coins',13);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (90,'Make Wiggler Squirm',13);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (91,'THI 100',13);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (92,'Roll into the Cage',14);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (93,'The Pit and the Pendulums',14);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (94,'Get a Hand',14);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (95,'Stomp on the Thwomp',14);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (96,'Timed Jumps on Moving Bars',14);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (97,'Stop Time for Red Coins',14);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (98,'TTC 100',14);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (99,'Cruiser Crossing the Rainbow',15);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (100,'The Big House in the Sky',15);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (101,'Coins Amassed in a Maze',15);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (102,'Swingin\' in the Breeze',15);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (103,'Tricky Triangles!',15);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (104,'Somewhere over the Rainbow',15);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (105,'RR 100',15);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (106,'Slide 1',16);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (107,'Slide 2',16);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (108,'Aquarium Reds',17);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (109,'BitDW Reds',18);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (110,'Wing Cap Reds',19);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (111,'Metal Cap Reds',20);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (112,'Vanish Cap Reds',21);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (113,'Toad 1',25);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (114,'Toad 2',25);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (115,'Toad 3',25);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (116,'Mips 1',25);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (117,'Mips 2',25);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (118,'Cloud Stage Reds',23);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (119,'BitFS Reds',22);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (120,'BitS Reds',24);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (121,'16 Star',26);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (122,'70 Star',26);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (123,'120 Star',26);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (124,'Single Bingo',26);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (125,'Double Bingo',26);
INSERT INTO `portfolioDB`.`Stars` (`StarId`,`Name`,`CourseId`) VALUES (126,'Triple Bingo',26);
