CREATE TABLE "Courses" (
    "CourseId" int NOT NULL,
    "Name" text NOT NULL,
    "Abbreviation" varchar(5) NULL,
    CONSTRAINT "PK_Courses" PRIMARY KEY ("CourseId")
);

CREATE TABLE "Stars" (
    "StarId" int NOT NULL,
    "Name" text NOT NULL,
    "CourseId" int NOT NULL,
    CONSTRAINT "PK_Stars" PRIMARY KEY ("StarId"),
    CONSTRAINT "FK_Stars_Courses_CourseId" FOREIGN KEY ("CourseId") REFERENCES "Courses" ("CourseId") ON DELETE CASCADE
);

CREATE TABLE "StarTimes" (
    "StarId" int NOT NULL,
    "UserId" varchar(255) NOT NULL,
    "LastUpdated" timestamp(6) NOT NULL,
    "Time" bigint NOT NULL,
    "VideoUrl" text NULL,
    CONSTRAINT "PK_StarTimes" PRIMARY KEY ("StarId", "UserId"),
    CONSTRAINT "FK_StarTimes_Stars_StarId" FOREIGN KEY ("StarId") REFERENCES "Stars" ("StarId") ON DELETE CASCADE,
    CONSTRAINT "FK_StarTimes_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Stars_CourseId" ON "Stars" ("CourseId");

CREATE INDEX "IX_StarTimes_UserId" ON "StarTimes" ("UserId");

BEGIN;

CREATE TABLE "ArchivedStarTimes" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Timestamp" timestamp(6) NOT NULL,
    "StarId" int NOT NULL,
    "UserId" varchar(255) NULL,
    "LastUpdated" timestamp(6) NOT NULL,
    "Time" bigint NOT NULL,
    "VideoUrl" text NULL,
    CONSTRAINT "PK_ArchivedStarTimes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ArchivedStarTimes_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_ArchivedStarTimes_Stars_StarId" FOREIGN KEY ("StarId") REFERENCES "Stars" ("StarId") ON DELETE CASCADE
);

CREATE INDEX "IX_ArchivedStarTimes_StarId" ON "ArchivedStarTimes" ("StarId");

CREATE INDEX "IX_ArchivedStarTimes_UserId" ON "ArchivedStarTimes" ("UserId");

COMMIT;

BEGIN;

ALTER TABLE "Stars" ADD COLUMN "RtaGuideUrl" text NULL;

ALTER TABLE "Stars" ADD COLUMN "SingleStarUrl" text NULL;

ALTER TABLE "Stars" ADD COLUMN "DisplayOrder" int NOT NULL DEFAULT 0;

COMMIT;