BEGIN;

ALTER TABLE "CardIds"
    DROP CONSTRAINT "PK_CardIds";

ALTER TABLE "CardIds"
    ADD CONSTRAINT "PK_CardIds"
    PRIMARY KEY ("Id", "Section", "CardCollectionId");

ALTER TABLE "DogTimes"
    ADD CONSTRAINT "PK_DogTimes"
    PRIMARY KEY ("Dog", "Timestamp");

ALTER TABLE "AspNetRoleClaims"
    ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE "AspNetUserClaims"
    ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT setval(
    pg_get_serial_sequence('"AspNetRoleClaims"', 'Id'),
    COALESCE(MAX("Id"), 1),
    MAX("Id") IS NOT NULL
)
FROM "AspNetRoleClaims";

SELECT setval(
    pg_get_serial_sequence('"AspNetUserClaims"', 'Id'),
    COALESCE(MAX("Id"), 1),
    MAX("Id") IS NOT NULL
)
FROM "AspNetUserClaims";

COMMIT;
