BEGIN;

CREATE SCHEMA legacy;

CREATE TABLE legacy."GameNightUserOrders" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "UserId" varchar(255) NOT NULL,
    "Order" integer NOT NULL,
    CONSTRAINT "PK_LegacyGameNightUserOrders" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_LegacyGameNightUserOrders_AspNetUsers_UserId"
        FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers" ("Id")
);

CREATE UNIQUE INDEX "IX_LegacyGameNightUserOrders_UserId"
    ON legacy."GameNightUserOrders" ("UserId");

CREATE TABLE legacy."__EFMigrationsHistory" (
    "MigrationId" varchar(95) NOT NULL,
    "ProductVersion" varchar(32) NOT NULL,
    CONSTRAINT "PK_LegacyEFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

COMMIT;
