// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Portfolio.Data;

namespace Portfolio.Migrations.Speedrun
{
    [DbContext(typeof(SpeedrunContext))]
    [Migration("20190702023011_SpeedrunInitialCreate")]
    partial class SpeedrunInitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("Portfolio.Models.StarTime", b =>
                {
                    b.Property<int>("StarId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Level");

                    b.Property<string>("Name");

                    b.Property<string>("Time");

                    b.HasKey("StarId");

                    b.ToTable("StarTimes");
                });
#pragma warning restore 612, 618
        }
    }
}
